# Generated by Django 3.2.4 on 2021-09-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImQzAnalysisFile',
            fields=[
                ('idx', models.AutoField(db_column='IDX', primary_key=True, serialize=False)),
                ('file_key', models.IntegerField(blank=True, db_column='FILE_KEY', null=True)),
                ('qz_num', models.IntegerField(blank=True, db_column='QZ_NUM', null=True)),
                ('qz_group', models.IntegerField(blank=True, db_column='QZ_GROUP', null=True)),
                ('qz_type', models.CharField(blank=True, db_column='QZ_TYPE', max_length=45, null=True)),
            ],
            options={
                'db_table': 'IM_QZ_ANALYSIS_FILE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImQzAnalysisJobword',
            fields=[
                ('aj_key', models.AutoField(db_column='AJ_KEY', primary_key=True, serialize=False)),
                ('file_key', models.IntegerField(blank=True, db_column='FILE_KEY', null=True)),
                ('qz_group', models.IntegerField(blank=True, db_column='QZ_GROUP', null=True)),
                ('word', models.CharField(blank=True, db_column='WORD', max_length=1000, null=True)),
                ('count', models.IntegerField(blank=True, db_column='COUNT', null=True)),
            ],
            options={
                'db_table': 'IM_QZ_ANALYSIS_JOBWORD',
                'managed': False,
            },
        ),
    ]
