# Generated by Django 3.2.4 on 2021-09-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0002_imqzanalysisfile_imqzanalysisjobword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImQzFile',
            fields=[
                ('file_key', models.AutoField(db_column='FILE_KEY', primary_key=True, serialize=False)),
                ('qz_group', models.IntegerField(blank=True, db_column='QZ_GROUP', null=True)),
                ('qz_platform', models.IntegerField(blank=True, db_column='QZ_PLATFORM', null=True)),
                ('user_key', models.IntegerField(blank=True, db_column='USER_KEY', null=True)),
                ('qz_num', models.IntegerField(blank=True, db_column='QZ_NUM', null=True)),
                ('qz_type', models.CharField(blank=True, db_column='QZ_TYPE', max_length=45, null=True)),
                ('group_code', models.IntegerField(blank=True, db_column='GROUP_CODE', null=True)),
                ('rtsp_url', models.CharField(blank=True, db_column='RTSP_URL', max_length=500, null=True)),
                ('file_url', models.CharField(blank=True, db_column='FILE_URL', max_length=500, null=True)),
                ('json_express', models.CharField(blank=True, db_column='JSON_EXPRESS', max_length=500, null=True)),
                ('json_action', models.CharField(blank=True, db_column='JSON_ACTION', max_length=500, null=True)),
                ('json_tone', models.CharField(blank=True, db_column='JSON_TONE', max_length=500, null=True)),
                ('json_db', models.CharField(blank=True, db_column='JSON_DB', max_length=500, null=True)),
                ('json_speed', models.CharField(blank=True, db_column='JSON_SPEED', max_length=500, null=True)),
                ('thum_url', models.CharField(blank=True, db_column='THUM_URL', max_length=500, null=True)),
                ('regdate', models.CharField(blank=True, db_column='REGDATE', max_length=45, null=True)),
                ('qz_org_tts', models.CharField(blank=True, db_column='QZ_ORG_TTS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'IM_QZ_FILE',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ImQzAnalysisFile',
        ),
    ]
